---
apiVersion: v1
kind: Namespace
metadata:
  name: clusters-sub

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clusters
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: clusters-sub
  project: ocloud-cluster-templates
  source:
    path: docs/samples/git-setup/clustertemplates
    repoURL: git@github.com:openshift-kni/oran-o2ims.git
    targetRevision: main
    # uncomment the below plugin if you will be adding the plugin binaries in the same repo->dir where
    # the sitconfig.yaml exist AND use the ../../hack/patch-argocd-dev.sh script to re-patch the deployment-repo-server
  #    plugin:
  #      name: kustomize-with-local-plugins
  ignoreDifferences: # recommended way to allow ACM controller to manage its fields. alternative approach documented below (1)
    - group: cluster.open-cluster-management.io
      kind: ManagedCluster
      managedFieldsManagers:
        - controller
  # (1) alternatively you can choose to ignore a specific path like so (replace managedFieldsManagers with jsonPointers)
  #      jsonPointers:
  #        - /metadata/labels/cloud
  #        - /metadata/labels/vendor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=background
      - RespectIgnoreDifferences=true