# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
inheritance: true
reviews:
  path_filters:
  - "!vendor/**"
  path_instructions:
    - path: '**'
      instructions: >-
        Focus on major issues impacting performance, readability,
        maintainability and security. Do not flag nitpicks. Do not
        suggest changes to pre-existing code that is not part of the diff.
  pre_merge_checks:
    docstrings:
      mode: off
