version: "2"
run:
  concurrency: 6
linters:
  default: none
  enable:
    - depguard
    - errcheck
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - goheader
    - gosec
    - govet
    - importas
    - ineffassign
    - loggercheck
    - misspell
    - nilnil
    - predeclared
    - promlinter
    - revive
    - sloglint
    #- staticcheck # TODO
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wrapcheck
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          files:
            - $all
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
    gocritic:
      enabled-checks:
        - commentedOutCode
        - nilValReturn
        - weakCond
        - octalLiteral
        - sloppyReassign
        - equalFold
        - indexAlloc
        - rangeExprCopy
        - appendCombine
        - boolExprSimplify
        - commentedOutImport
        - docStub
        - emptyFallthrough
        - emptyStringTest
        - hexLiteral
        - methodExprCall
        - stringXbytes
        - typeAssertChain
        - unlabelStmt
        - yodaStyleExpr
        - initClause
        - nestingReduce
        - ptrToRefParam
        - typeUnparen
        - unnecessaryBlock
        - paramTypeCombine
    goheader:
      values:
        const:
          COMPANY: Red Hat
      template: |-
        SPDX-FileCopyrightText: {{ COMPANY }}

        SPDX-License-Identifier: Apache-2.0
    importas:
      alias:
        - pkg: k8s.io/api/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: k8s.io/apimachinery/pkg/apis/(\w+)/(v[\w\d]+)
          alias: $1$2
        - pkg: github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/v1alpha1
          alias: hwmgmtv1alpha1
        - pkg: github.com/openshift-kni/oran-o2ims/api/hardwaremanagement/plugins/v1alpha1
          alias: pluginsv1alpha1
        - pkg: github.com/openshift-kni/oran-o2ims/api/inventory/v1alpha1
          alias: inventoryv1alpha1
        - pkg: github.com/openshift-kni/oran-o2ims/api/provisioning/v1alpha1
          alias: provisioningv1alpha1
        - pkg: github.com/openshift-kni/oran-o2ims/hwmgr-plugins/api/client/utils
          alias: hwmgrclientutils
        - pkg: github.com/openshift-kni/oran-o2ims/hwmgr-plugins/controller/utils
          alias: hwmgrutils
        - pkg: github.com/openshift-kni/oran-o2ims/internal/controllers/utils
          alias: ctlrutils
        - pkg: github.com/openshift-kni/oran-o2ims/internal/service/cluster/utils
          alias: svcclusterutils
        - pkg: github.com/openshift-kni/oran-o2ims/internal/service/common/utils
          alias: svcutils
        - pkg: github.com/openshift-kni/oran-o2ims/internal/service/resources/utils
          alias: svcresourceutils
        - pkg: github.com/openshift-kni/oran-o2ims/test/utils
          alias: testutils
    revive:
      rules:
        - name: if-return
          severity: warning
          disabled: true
        - name: string-format
          arguments:
            - - core.WriteError[1].Message
              - /^([^A-Z]|$)/
              - must not start with a capital letter
            - - fmt.Errorf[0]
              - /^([^A-Z]|$)/
              - must not start with a capital letter
            - - fmt.Errorf[0]
              - /(^|[^\.!?])$/
              - must not end in punctuation
            - - panic
              - /^[^\n]*$/
              - must not contain line breaks
          severity: warning
          disabled: false
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - .WrapPrefixf(
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
