apiVersion: clcm.openshift.io/v1alpha1
kind: HardwareTemplate
metadata:
  name: std-dell-r740-green-xr8620t-blue
  namespace: oran-o2ims
spec:
  nodeGroupData:
    - name: master
      role: master
      # hwProfile is optional. It can also be specified (or overridden) via
      # templateParameters.hwTemplateParameters.nodeGroupData.<name>.hwProfile
      # in the ProvisioningRequest.
      # hwProfile: dell-r740-bios-2.22.2-bmc-7.00.00.173
      resourceSelector:
        "resourceselector.clcm.openshift.io/server-type": "R740"
        "resourceselector.clcm.openshift.io/server-colour": "green"
        "hardwaredata/cpu_arch": "x86_64"
    - name: worker
      role: worker
      # hwProfile is optional. It can also be specified (or overridden) via
      # templateParameters.hwTemplateParameters.nodeGroupData.<name>.hwProfile
      # in the ProvisioningRequest.
      # hwProfile: dell-xr8620t-bios-2.3.5-bmc-7.10.70.10
      resourceSelector:
        "resourceselector.clcm.openshift.io/server-type": "XR8620t"
        "resourceselector.clcm.openshift.io/server-colour": "blue"
        "hardwaredata/cpu_arch": "x86_64"
  hardwareProvisioningTimeout: "4h"
