apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: artifacts-server-tls
  creationTimestamp: null
  name: oran-o2ims-artifacts-server
