apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    role: provisioner-role
  name: oran-o2ims-provisioner-role
rules:
- nonResourceURLs:
  - /o2ims-infrastructureArtifacts/*
  - /o2ims-infrastructureArtifacts/api_versions
  - /o2ims-infrastructureArtifacts/v1/managedInfrastructureTemplates
  - /o2ims-infrastructureArtifacts/v1/managedInfrastructureTemplates/*
  - /o2ims-infrastructureProvisioning/*
  - /o2ims-infrastructureProvisioning/api_versions
  verbs:
  - get
- nonResourceURLs:
  - /o2ims-infrastructureProvisioning/v1/provisioningRequests
  verbs:
  - get
  - create
- nonResourceURLs:
  - /o2ims-infrastructureProvisioning/v1/provisioningRequests/*
  verbs:
  - get
  - delete
- nonResourceURLs:
  - /o2ims-infrastructureProvisioning/v1/provisioningRequests/*
  verbs:
  - update
