apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    role: maintainer-role
  name: oran-o2ims-maintainer-role
rules:
- nonResourceURLs:
  - /o2ims-infrastructureMonitoring/v1/alarms/*
  verbs:
  - patch
- nonResourceURLs:
  - /o2ims-infrastructureMonitoring/v1/alarmServiceConfiguration
  verbs:
  - get
  - patch
  - update
