apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oran-o2ims
  name: oran-o2ims-clcm-hardwareprofile-editor-role
rules:
- apiGroups:
  - clcm.openshift.io
  resources:
  - hardwareprofiles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clcm.openshift.io
  resources:
  - hardwareprofiles/status
  verbs:
  - get
