apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  labels:
    role: reader-role
  name: oran-o2ims-reader-role
rules:
- nonResourceURLs:
  - /O2ims_infrastructureInventory/api_versions
  - /O2ims_infrastructureInventory/v2
  - /O2ims_infrastructureInventory/v2/api_versions
  - /O2ims_infrastructureInventory/v2/resourceTypes
  - /O2ims_infrastructureInventory/v2/resourceTypes/*
  - /O2ims_infrastructureInventory/v2/resourcePools
  - /O2ims_infrastructureInventory/v2/resourcePools/*
  - /O2ims_infrastructureInventory/v2/alarmDictionaries
  - /O2ims_infrastructureInventory/v2/alarmDictionaries/*
  - /O2ims_infrastructureInventory/v2/locations
  - /O2ims_infrastructureInventory/v2/locations/*
  - /O2ims_infrastructureInventory/v2/oCloudSites
  - /O2ims_infrastructureInventory/v2/oCloudSites/*
  - /O2ims_infrastructureMonitoring/*
  - /O2ims_infrastructureMonitoring/api_versions
  - /O2ims_infrastructureCluster/*
  - /O2ims_infrastructureCluster/api_versions
  - /O2ims_infrastructureArtifacts/*
  - /O2ims_infrastructureArtifacts/api_versions
  - /O2ims_infrastructureArtifacts/v1/managedInfrastructureTemplates
  - /O2ims_infrastructureArtifacts/v1/managedInfrastructureTemplates/*
  - /O2ims_infrastructureProvisioning/*
  - /O2ims_infrastructureProvisioning/api_versions
  verbs:
  - get
- nonResourceURLs:
  - /O2ims_infrastructureMonitoring/v1/alarmSubscriptions
  - /O2ims_infrastructureInventory/v2/subscriptions
  - /O2ims_infrastructureCluster/v1/subscriptions
  - /O2ims_infrastructureProvisioning/v1/provisioningRequests
  verbs:
  - get
- nonResourceURLs:
  - /O2ims_infrastructureMonitoring/v1/alarmSubscriptions/*
  - /O2ims_infrastructureInventory/v2/subscriptions/*
  - /O2ims_infrastructureCluster/v1/subscriptions/*
  - /O2ims_infrastructureProvisioning/v1/provisioningRequests/*
  verbs:
  - get
- nonResourceURLs:
  - /O2ims_infrastructureMonitoring/v1/alarmServiceConfiguration
  verbs:
  - get
