---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-o2ims-provisioning-oran-org-v1alpha1-provisioningrequest
  failurePolicy: Fail
  name: provisioningrequests.o2ims.provisioning.oran.org
  rules:
  - apiGroups:
    - o2ims.provisioning.oran.org
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - provisioningrequests
  sideEffects: None
