---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clcm-openshift-io-v1alpha1-provisioningrequest
  failurePolicy: Fail
  name: provisioningrequests.clcm.openshift.io
  rules:
  - apiGroups:
    - clcm.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - provisioningrequests
  sideEffects: None
