---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clcm-openshift-io-v1alpha1-provisioningrequest
  failurePolicy: Fail
  name: provisioningrequests.clcm.openshift.io
  rules:
  - apiGroups:
    - clcm.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - provisioningrequests
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ocloud-openshift-io-v1alpha1-location
  failurePolicy: Ignore
  name: locations.ocloud.openshift.io
  rules:
  - apiGroups:
    - ocloud.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - locations
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ocloud-openshift-io-v1alpha1-ocloudsite
  failurePolicy: Ignore
  name: ocloudsites.ocloud.openshift.io
  rules:
  - apiGroups:
    - ocloud.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - ocloudsites
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ocloud-openshift-io-v1alpha1-resourcepool
  failurePolicy: Ignore
  name: resourcepools.ocloud.openshift.io
  rules:
  - apiGroups:
    - ocloud.openshift.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - resourcepools
  sideEffects: None
