apiVersion: v1
kind: ConfigMap
metadata:
  name: policytemplate-full-du-defaults-v1
  namespace: sno-ran-full-du-v4-Y-Z
data:
  # clusterConfigurationTimeout is optional.
  # The value should be a duration string
  # (e.g., "40m" for 40 minutes)
  clusterConfigurationTimeout: "40m"
  policytemplate-defaults: |
    cluster-log-fwd-filters-labels: '{"label1": "test1", "label2": "test2"}'
    cluster-log-fwd-outputs-url: "tcp://10.46.55.190:9092/test"
    cpu-isolated: 0-1,64-65
    cpu-reserved: 2-10
    hugepages-count: "32"
    hugepages-default: 1G
    hugepages-size: 1G
    oadp-s3url: http://s3storage.example.com:9000
    ptpcfgslave-profile-interface: ens15f1
    sriov-fec-bbDevConfig: '{"acc100": {"pfMode": false, "numVfBundles": 16, "maxQueueSize": 1024, "uplink5G": {"numQueueGroups": 4, "numAqsPerGroups": 16, "aqDepthLog2": 4}, "downlink5G": {"numQueueGroups": 4, "numAqsPerGroups": 1, "aqDepthLog2": 4}, "uplink4G": {"numQueueGroups": 0, "numAqsPerGroups": 1, "aqDepthLog2": 4}, "downlink4G": {"numQueueGroups": 0, "numAqsPerGroups": 1, "aqDepthLog2": 4}}}'
    sriov-fec-pciAddress: 0000:b4:00.1
    sriov-fec-pfDriver: pci-pf-stub
    sriov-fec-vfDriver: vfio-pci
    sriov-network-pfNames-1: '["ens4f1"]'
    sriov-network-pfNames-2: '["ens4f2"]'
    sriov-network-vlan-1: "114"
    sriov-network-vlan-2: "111"
    storage-lv-devicePaths-1: /dev/disk/by-path/pci-0000:62:00.0-scsi-0:2:8:0
    install-plan-approval: Automatic
