# Prometheus Monitor for O2IMS service pods (alarms, cluster, resource, provisioning, artifacts)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: servicemonitor
    app.kubernetes.io/instance: o2ims-services-metrics-monitor
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: oran-o2ims
    app.kubernetes.io/part-of: oran-o2ims
    app.kubernetes.io/managed-by: kustomize
  name: o2ims-services-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: api
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      oran-o2ims/metrics: "true"
