apiVersion: clcm.openshift.io/v1alpha1
kind: HardwareTemplate
metadata:
  name: dell-r740-blue
  namespace: oran-o2ims
spec:
  hardwarePluginRef: metal3-hwplugin
  nodeGroupData:
    - name: controller
      role: master
      # hwProfile is optional. It can also be specified (or overridden) via
      # templateParameters.hwTemplateParameters.nodeGroupData.<name>.hwProfile
      # in the ProvisioningRequest.
      hwProfile: rh-profile-r740-bios-settings
      resourceSelector:
        "resourceselector.clcm.openshift.io/server-type": "R740"
        "resourceselector.clcm.openshift.io/server-colour": "blue"
        "hardwaredata/cpu_arch": "x86_64"
        "hardwaredata/num_threads;>=": "64"
  hardwareProvisioningTimeout: "60m"
