apiVersion: siteconfig.open-cluster-management.io/v1alpha1
kind: ClusterInstance
metadata:
  name: "{{ .Cluster.clusterName }}"
  namespace: "{{ .Cluster.clusterName }}"
spec:
  # Mandatory fields at cluster-level
  baseDomain: "{{ .Cluster.baseDomain }}"
  clusterImageSetNameRef: "{{ .Cluster.clusterImageSetNameRef }}"
  clusterName: "{{ .Cluster.clusterName }}"
  pullSecretRef:
    name: "{{ .Cluster.pullSecretRef.name }}"
  templateRefs:
  {{- range .Cluster.templateRefs }}
    - name: "{{ .name }}"
      namespace: "{{ .namespace }}"
  {{- end }}
  # Optional fields at cluster-level
{{- if .Cluster.additionalNTPSources }}
  additionalNTPSources:
{{ .Cluster.additionalNTPSources | toYaml | indent 4 }}
{{- end }}
{{- if .Cluster.apiVIPs }}
  apiVIPs:
{{ .Cluster.apiVIPs | toYaml | indent 4 }}
{{- end }}
{{- if .Cluster.caBundleRef.name }}
  caBundleRef:
    name: "{{ .Cluster.caBundleRef.name }}"
{{- end }}
{{- if .Cluster.clusterLabels }}
  clusterLabels:
{{ .Cluster.clusterLabels | toYaml | indent 4 }}
{{- end }}
{{- if .Cluster.clusterType }}
  clusterType: "{{ .Cluster.clusterType }}"
{{- end }}
{{- if .Cluster.clusterNetwork }}
  clusterNetwork:
  {{- range .Cluster.clusterNetwork }}
    - cidr: "{{ .cidr }}"
      {{- if .hostPrefix }}
      hostPrefix: {{ .hostPrefix }}
      {{- end }}
  {{- end }}
{{- end }}
{{- if .Cluster.machineNetwork }}
  machineNetwork:
  {{- range .Cluster.machineNetwork }}
    - cidr: "{{ .cidr }}"
  {{- end }}
{{- end }}
{{- if .Cluster.networkType }}
  networkType: "{{ .Cluster.networkType }}"
{{- end }}
{{- if .Cluster.cpuPartitioningMode }}
  cpuPartitioningMode: "{{ .Cluster.cpuPartitioningMode }}"
{{- end }}
{{- if .Cluster.diskEncryption }}
  diskEncryption:
{{ .Cluster.diskEncryption | toYaml | indent 4 }}
{{- end }}
{{- if .Cluster.extraAnnotations }}
  extraAnnotations:
{{ .Cluster.extraAnnotations | toYaml | indent 4 }}
{{- end }}
{{- if .Cluster.extraManifestsRefs }}
  extraManifestsRef:
  {{- range .Cluster.extraManifestsRefs }}
    - name: "{{ .name }}"
  {{- end }}
{{- end }}
{{- if .Cluster.holdInstallation }}
  holdInstallation: {{ .Cluster.holdInstallation }}
{{- end }}
{{- if .Cluster.ignitionConfigOverride }}
  ignitionConfigOverride: {{ .Cluster.ignitionConfigOverride | quote }}
{{- end }}
{{- if .Cluster.installConfigOverrides }}
  installConfigOverrides: {{ .Cluster.installConfigOverrides | quote }}
{{- end }}
{{- if .Cluster.ingressVIPs }}
  ingressVIPs:
{{ .Cluster.ingressVIPs | toYaml | indent 4 }}
{{- end }}
{{- if .Cluster.proxy }}
  proxy:
{{ .Cluster.proxy | toYaml | indent 4 }}
{{- end }}
{{- if .Cluster.serviceNetwork }}
  serviceNetwork:
  {{- range .Cluster.serviceNetwork }}
    - cidr: "{{ .cidr }}"
  {{- end }}
{{- end }}
{{- if .Cluster.sshPublicKey }}
  sshPublicKey: "{{ .Cluster.sshPublicKey }}"
{{- end }}
{{- if .Cluster.suppressedManifests }}
  suppressedManifests:
{{ .Cluster.suppressedManifests | toYaml | indent 4 }}
{{- end }}
  nodes:
  {{- range .Cluster.nodes }}
    # Mandatory fields at node-level
    {{- $nodeName := splitList "." .hostName | first }}
    {{- $bmcCredname := printf "%s-bmc-secret" $nodeName | quote }}
    {{- if .bmcCredentialsName.name }}
      {{- $bmcCredname = .bmcCredentialsName.name | quote }}
    {{- end }}
    - bmcAddress: "{{ .bmcAddress }}"
      bmcCredentialsName:
        name: {{ $bmcCredname }}
      bootMACAddress: "{{ .bootMACAddress }}"
      bootMode: "{{ .bootMode }}"
      hostName: "{{ .hostName }}"
      templateRefs:
      {{- range .templateRefs }}
        - name: "{{ .name }}"
          namespace: "{{ .namespace }}"
      {{- end }}
      # Optional fields at node-level
      {{- if .automatedCleaningMode }}
      automatedCleaningMode: "{{ .automatedCleaningMode }}"
      {{- end }}
      {{- if .extraAnnotations }}
      extraAnnotations:
{{ .extraAnnotations | toYaml | indent 8 }}
      {{- end }}
      {{- if .ignitionConfigOverride }}
      ignitionConfigOverride: {{ .ignitionConfigOverride | quote }}
      {{- end }}
      {{- if .installerArgs }}
      installerArgs: {{ .installerArgs | quote }}
      {{- end }}
      {{- if .ironicInspect }}
      ironicInspect: "{{ .ironicInspect }}"
      {{- end }}
      {{- if .nodeLabels }}
      nodeLabels:
{{ .nodeLabels | toYaml | indent 8 }}
      {{- end }}
      {{- if .nodeNetwork }}
      nodeNetwork:
        config:
{{ .nodeNetwork.config | toYaml | indent 10 }}
        interfaces:
        {{- range .nodeNetwork.interfaces }}
          - macAddress: "{{ .macAddress }}"
            name: "{{ .name }}"
        {{- end }}
      {{- end }}
      {{- if .role }}
      role: "{{ .role }}"
      {{- end }}
      {{- if .rootDeviceHints }}
      rootDeviceHints:
{{ .rootDeviceHints | toYaml | indent 8 }}
      {{- end }}
      {{- if .suppressedManifests }}
      suppressedManifests:
{{ .suppressedManifests | toYaml | indent 8 }}
      {{- end }}
  {{- end }}
