# permissions for end users to view clustertemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clustertemplate-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oran-o2ims
    app.kubernetes.io/part-of: oran-o2ims
    app.kubernetes.io/managed-by: kustomize
  name: clustertemplate-viewer-role
rules:
- apiGroups:
  - clcm.openshift.io
  resources:
  - clustertemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clcm.openshift.io
  resources:
  - clustertemplates/status
  verbs:
  - get
