apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: artifacts-server
rules:
- apiGroups:
  - clcm.openshift.io
  resources:
  - clustertemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
