# permissions for end users to view hardwareplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oran-o2ims
    app.kubernetes.io/managed-by: kustomize
  name: hardwaremanagement-hardwareplugin-viewer-role
rules:
- apiGroups:
  - hardwaremanagement.openshift.io
  resources:
  - hardwareplugins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hardwaremanagement.openshift.io
  resources:
  - hardwareplugins/status
  verbs:
  - get
