# permissions for end users to edit hardwareplugins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oran-o2ims
    app.kubernetes.io/managed-by: kustomize
  name: hardwaremanagement-hardwareplugin-editor-role
rules:
- apiGroups:
  - hardwaremanagement.openshift.io
  resources:
  - hardwareplugins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hardwaremanagement.openshift.io
  resources:
  - hardwareplugins/status
  verbs:
  - get
