apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: controller-manager-metrics-tls
  name: controller-manager-metrics-service
  namespace: system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
