apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: networkpolicy-manager-role
  namespace: system
rules:
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
