# permissions for end users to view hardwareprofiles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: oran-o2ims
    app.kubernetes.io/managed-by: kustomize
  name: o2ims-hardwaremanagement-hardwareprofile-viewer-role
rules:
- apiGroups:
  - o2ims-hardwaremanagement.openshift.io
  resources:
  - hardwareprofiles
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - o2ims-hardwaremanagement.openshift.io
  resources:
  - hardwareprofiles/status
  verbs:
  - get
