# permissions for end users to edit clustertemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: clustertemplate-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oran-o2ims
    app.kubernetes.io/part-of: oran-o2ims
    app.kubernetes.io/managed-by: kustomize
  name: clustertemplate-editor-role
rules:
- apiGroups:
  - o2ims.provisioning.oran.org
  resources:
  - clustertemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - o2ims.provisioning.oran.org
  resources:
  - clustertemplates/status
  verbs:
  - get
