# permissions for end users to view Inventory CR.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: inventory-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oran-o2ims
    app.kubernetes.io/part-of: oran-o2ims
    app.kubernetes.io/managed-by: kustomize
  name: inventory-viewer-role
rules:
- apiGroups:
  - o2ims.oran.openshift.io
  resources:
  - inventories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - o2ims.oran.openshift.io
  resources:
  - inventories/status
  verbs:
  - get
