# permissions for end users to edit Inventory CR.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: inventory-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: oran-o2ims
    app.kubernetes.io/part-of: oran-o2ims
    app.kubernetes.io/managed-by: kustomize
  name: inventory-editor-role
rules:
- apiGroups:
  - ocloud.openshift.io
  resources:
  - inventories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocloud.openshift.io
  resources:
  - inventories/status
  verbs:
  - get
