apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: reader-role
  labels:
    role: reader-role
rules:
- nonResourceURLs:
  - /O2ims_infrastructureInventory/api_versions
  - /O2ims_infrastructureInventory/v2
  - /O2ims_infrastructureInventory/v2/api_versions
  - /O2ims_infrastructureInventory/v2/resourceTypes
  - /O2ims_infrastructureInventory/v2/resourceTypes/*
  - /O2ims_infrastructureInventory/v2/resourcePools
  - /O2ims_infrastructureInventory/v2/resourcePools/*
  - /O2ims_infrastructureInventory/v2/alarmDictionaries
  - /O2ims_infrastructureInventory/v2/alarmDictionaries/*
  - /O2ims_infrastructureInventory/v2/locations
  - /O2ims_infrastructureInventory/v2/locations/*
  - /O2ims_infrastructureInventory/v2/oCloudSites
  - /O2ims_infrastructureInventory/v2/oCloudSites/*
  - /O2ims_infrastructureMonitoring/*
  - /O2ims_infrastructureMonitoring/api_versions
  - /O2ims_infrastructureCluster/*
  - /O2ims_infrastructureCluster/api_versions
  - /O2ims_infrastructureArtifacts/*
  - /O2ims_infrastructureArtifacts/api_versions
  - /O2ims_infrastructureArtifacts/v1/managedInfrastructureTemplates
  - /O2ims_infrastructureArtifacts/v1/managedInfrastructureTemplates/*
  - /O2ims_infrastructureProvisioning/*
  - /O2ims_infrastructureProvisioning/api_versions
  verbs:
  - get
- nonResourceURLs:
  - /O2ims_infrastructureMonitoring/v1/alarmSubscriptions
  - /O2ims_infrastructureInventory/v2/subscriptions
  - /O2ims_infrastructureCluster/v1/subscriptions
  - /O2ims_infrastructureProvisioning/v1/provisioningRequests
  verbs:
  - get
- nonResourceURLs:
  - /O2ims_infrastructureMonitoring/v1/alarmSubscriptions/*
  - /O2ims_infrastructureInventory/v2/subscriptions/*
  - /O2ims_infrastructureCluster/v1/subscriptions/*
  - /O2ims_infrastructureProvisioning/v1/provisioningRequests/*
  verbs:
  - get
- nonResourceURLs:
  - /O2ims_infrastructureMonitoring/v1/alarmServiceConfiguration
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: maintainer-role
  labels:
    role: maintainer-role
rules:
- nonResourceURLs:
  - /O2ims_infrastructureMonitoring/v1/alarms/*
  verbs:
  - patch
- nonResourceURLs:
  - /O2ims_infrastructureMonitoring/v1/alarmServiceConfiguration
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: subscriber-role
  labels:
    role: subscriber-role
rules:
- nonResourceURLs:
  - /O2ims_infrastructureMonitoring/v1/alarmSubscriptions
  - /O2ims_infrastructureInventory/v2/subscriptions
  - /O2ims_infrastructureCluster/v1/subscriptions
  verbs:
  - get
  - create
- nonResourceURLs:
  - /O2ims_infrastructureMonitoring/v1/alarmSubscriptions/*
  - /O2ims_infrastructureInventory/v2/subscriptions/*
  - /O2ims_infrastructureCluster/v1/subscriptions/*
  verbs:
  - get
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: provisioner-role
  labels:
    role: provisioner-role
rules:
- nonResourceURLs:
  - /O2ims_infrastructureArtifacts/*
  - /O2ims_infrastructureArtifacts/api_versions
  - /O2ims_infrastructureArtifacts/v1/managedInfrastructureTemplates
  - /O2ims_infrastructureArtifacts/v1/managedInfrastructureTemplates/*
  - /O2ims_infrastructureProvisioning/*
  - /O2ims_infrastructureProvisioning/api_versions
  verbs:
  - get
- nonResourceURLs:
  - /O2ims_infrastructureProvisioning/v1/provisioningRequests
  verbs:
  - get
  - create
- nonResourceURLs:
  - /O2ims_infrastructureProvisioning/v1/provisioningRequests/*
  verbs:
  - get
  - delete
- nonResourceURLs:
  - /O2ims_infrastructureProvisioning/v1/provisioningRequests/*
  verbs:
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deployer-role
  labels:
    role: deployer-role
rules:
- nonResourceURLs:
  - /O2ims_infrastructureInventory/v2/deploymentManagers
  - /O2ims_infrastructureInventory/v2/deploymentManagers/*
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: admin-role
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      role: reader-role
  - matchLabels:
      role: subscriber-role
  - matchLabels:
      role: maintainer-role
  - matchLabels:
      role: provisioner-role
  - matchLabels:
      role: deployer-role
