apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: alarms-server
  namespace: system
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - delete
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - get
  - list
  - watch
  - create
  - delete
  - update
  - patch
