apiVersion: v1
kind: ServiceAccount
metadata:
  name: alarms-server
  namespace: system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: alarms-server-tls
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: artifacts-server
  namespace: system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: artifacts-server-tls
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-server
  namespace: system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: cluster-server-tls
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hardwaremanager-server
  namespace: system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: hardwaremanager-server-tls
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: provisioning-server
  namespace: system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: provisioning-server-tls
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: resource-server
  namespace: system
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: resource-server-tls
