apiVersion: v1
kind: ConfigMap
metadata:
  name: policytemplate-defaults-v1
  namespace: sno-ran-du-v4-16
data:
  # clusterConfigurationTimeout is optional.
  # The value should be a duration string
  # (e.g., "40m" for 40 minutes)
  clusterConfigurationTimeout: "40m"
  policytemplate-defaults: |
    sriov-network-vlan-1: "140"
    sriov-network-vlan-2: "150"
    cpu-isolated: "0-1,64-65"
    cpu-reserved: "2-10"
    hugepages-default: "1G"
    hugepages-size: "1G"
    hugepages-count: "32"
    install-plan-approval: "Automatic"
