namespace: oran-o2ims

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: o-cloud-db-postgresql-cfg
    files:
      - postgresql-cfg/postgresql.conf
  - name: o-cloud-db-postgresql-start
    files:
      - postgresql-start/init.sh

secretGenerator:
  - name: o-cloud-db-db-secret
    literals:
      - admin-password=by1yYW4= # o-ran
