apiVersion: clcm.openshift.io/v1alpha1
kind: FirmwareCatalog
metadata:
  name: firmwarecatalog-sample
  namespace: oran-o2ims
spec:
  images:
    - name: bios-dell-xr8620t
      version: "2.22.2"
      component: bios
      url: https://firmware.example.com/bios-xr8620t-2.22.2.bin
