resources:

# Inventory:
- v1alpha1_inventory.yaml
- v1alpha1_location.yaml
- v1alpha1_ocloudsite.yaml
- v1alpha1_resourcepool.yaml

# Hardware management:
- v1alpha1_allocatednode.yaml
- v1alpha1_nodeallocationrequest.yaml
- v1alpha1_hardwareprofile.yaml

# Provisioning:
- v1alpha1_clustertemplate.yaml
- v1alpha1_provisioningrequest.yaml

