apiVersion: clcm.openshift.io/v1alpha1
kind: HardwareTemplate
metadata:
  name: hwtemplate-sample
  namespace: oran-o2ims
spec:
  nodeGroupData:
    - name: master
      role: master
      resourceSelector:
        "resourceselector.clcm.openshift.io/server-type": "xr8620t"
        "resourceselector.clcm.openshift.io/server-colour": "blue"
  hardwareProvisioningTimeout: "90m"
