apiVersion: plugins.clcm.openshift.io/v1alpha1
kind: NodeAllocationRequest
metadata:
  name: metal3-b12f3e77848a4002bf40
  namespace: oran-o2ims
spec:
  callback:
    callbackURL: https://oran-o2ims-nar-callback-service.oran-o2ims.svc.cluster.local:8090/nar-callback/v1/provisioning-requests/123e4567-e89b-12d3-a456-426614174000
  clusterId: site-sno-du-1123e4567-e89b-12d3-a456-426614174000
  configTransactionId: 1
  hardwarePluginRef: metal3-hwplugin
  hardwareProvisioningTimeout: 90m
  nodeGroup:
  - nodeGroupData:
      hwProfile: hardwareprofile-sample
      name: master
      resourceSelector:
        resourceselector.clcm.openshift.io/server-colour: blue
        resourceselector.clcm.openshift.io/server-type: xr8620t
      role: master
    size: 1
  site: local-west-12345
status:
  conditions:
  - lastTransitionTime: "2026-03-03T15:04:57Z"
    message: Created
    reason: Completed
    status: "True"
    type: Provisioned
  hwMgrPlugin:
    observedGeneration: 1
  observedConfigTransactionId: 0
  properties:
    nodeNames:
    - metal3-hwplugin-site-sno-du-1-xr8620t-pool-xr8620txserver1
