apiVersion: clcm.openshift.io/v1alpha1
kind: HardwareProfile
metadata:
  name: hardwareprofile-sample
  namespace: oran-o2ims
spec:
  bios:
    attributes:
      SriovGlobalEnable: Enabled
      SysProfile: Custom
      WorkloadProfile: TelcoOptimizedProfile
  biosFirmware: dell-xr8620t-bios-2.7.5
  bmcFirmware: dell-xr8620t-bmc-7.20.70.50
status:
  conditions: []
