apiVersion: plugins.clcm.openshift.io/v1alpha1
kind: AllocatedNode
metadata:
  name: metal3-hwplugin-site-sno-du-1-xr8620t-pool-xr8620txserver1
  namespace: oran-o2ims
spec:
  groupName: master
  hwMgrNodeId: xr8620txserver1
  hwMgrNodeNs: xr8620t-pool
  hwProfile: hardwareprofile-sample
  nodeAllocationRequest: metal3-b12f3e77848a4002bf40
status:
  bmc:
    address: idrac-virtualmedia+https://192.0.2.100/redfish/v1/Systems/System.Embedded.1
    credentialsName: bmc-secret-xr8620txserver1
  conditions:
  - lastTransitionTime: "2026-03-03T15:04:57Z"
    message: Provisioned
    reason: Completed
    status: "True"
    type: Provisioned
  hwProfile: hardwareprofile-sample
  interfaces:
  - label: sriov-1
    macAddress: 02:00:00:00:01:01
    name: ens2f0
  - label: ""
    macAddress: 02:00:00:00:01:02
    name: ens3f3
  - label: data-interface
    macAddress: 02:00:00:00:01:03
    name: ens3f1
  - label: ""
    macAddress: 02:00:00:00:01:04
    name: ens2f3
  - label: sriov-2
    macAddress: 02:00:00:00:01:05
    name: ens2f1
  - label: ""
    macAddress: 02:00:00:00:01:06
    name: ens3f2
  - label: boot-interface
    macAddress: 02:00:00:00:01:07
    name: ens3f0
  - label: ""
    macAddress: 02:00:00:00:01:08
    name: ens2f2
