# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: narcallback
output: ../../server/nar-callback/generated.go

generate:
  std-http-server: true
  client: false
  models: true
  embedded-spec: true
  strict-server: true

output-options:
  skip-fmt: false
  skip-prune: false
  nullable-type: true
  name-normalizer: ToCamelCaseWithDigits
