# We use this IDMS in the Conforma tests to check for fips compliance.
# https://github.com/konflux-ci/build-definitions/tree/main/task/fbc-fips-check-oci-ta/0.1
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: o-cloud-image-digest-mirror-set
spec:
  imageDigestMirrors:
    - mirrors:
        - quay.io/redhat-user-workloads/telco-5g-tenant/o-cloud-manager-4-21
      source: registry.redhat.io/openshift4/o-cloud-manager-rhel9-operator
    - mirrors:
        - quay.io/redhat-user-workloads/telco-5g-tenant/o-cloud-manager-bundle-4-21
      source: registry.redhat.io/openshift4/o-cloud-manager-operator-bundle
