apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-kni/oran-o2ims?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/pull_request_number: '{{pull_request_number}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "true"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "pull_request" &&
      target_branch == "main" &&
      (
        '.tekton/o-cloud-manager-4-20-pull-request.yaml'.pathChanged() ||
        '.tekton/build-pipeline.yaml'.pathChanged() ||
        'telco5g-konflux'.pathChanged() ||
        'telco5g-konflux/***'.pathChanged() ||
        '.konflux/Dockerfile'.pathChanged() ||
        'go.mod'.pathChanged() ||
        'go.sum'.pathChanged() ||
        'main.go'.pathChanged() ||
        'api/***'.pathChanged() ||
        'hack/***'.pathChanged() ||
        'internal/***'.pathChanged() ||
        'pkg/***'.pathChanged() ||
        'vendor/***'.pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: o-cloud-manager-4-20
    appstudio.openshift.io/component: o-cloud-manager-4-20
    pipelines.appstudio.openshift.io/type: build
  name: o-cloud-manager-4-20-on-pull-request
  namespace: telco-5g-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/telco-5g-tenant/o-cloud-manager-4-20:on-pr-{{revision}}
    - name: image-expires-after
      value: 5d
    - name: build-platforms
      value:
        - linux/x86_64
    - name: dockerfile
      value: .konflux/Dockerfile
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: ""
    - name: build-source-image
      value: "true"
    - name: skip-sast-coverity
      value: "true"
    - name: additional-tags
      value: []
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-o-cloud-manager-4-20
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
