apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-kni/oran-o2ims?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch == "main" && files.all != [".konflux/overlay/pin_images.in.yaml"]
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: o-cloud-manager-4-19
    appstudio.openshift.io/component: o-cloud-manager-4-19
    pipelines.appstudio.openshift.io/type: build
  name: o-cloud-manager-4-19-on-push
  namespace: telco-5g-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/telco-5g-tenant/o-cloud-manager-4-19:{{revision}}
    - name: dockerfile
      value: .konflux/Dockerfile
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: ""
    - name: build-source-image
      value: "true"
  pipelineRef:
    name: o-cloud-manager-4-19-build
  taskRunTemplate: {}
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
