apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-kni/oran-o2ims?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" &&
      target_branch == "main" &&
      (
        '.konflux/Dockerfile'.pathChanged() ||
        '.tekton/build-pipeline.yaml'.pathChanged() ||
        '.tekton/o-cloud-manager-4-22-push.yaml'.pathChanged() ||
        'api/***'.pathChanged() ||
        'go.mod'.pathChanged() ||
        'go.sum'.pathChanged() ||
        'hack/***'.pathChanged() ||
        'internal/***'.pathChanged() ||
        'main.go'.pathChanged() ||
        'pkg/***'.pathChanged() ||
        'telco5g-konflux'.pathChanged() ||
        'telco5g-konflux/***'.pathChanged() ||
        'vendor/***'.pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: o-cloud-manager-4-22
    appstudio.openshift.io/component: o-cloud-manager-4-22
    pipelines.appstudio.openshift.io/type: build
  name: o-cloud-manager-4-22-on-push
  namespace: telco-5g-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/telco-5g-tenant/o-cloud-manager-4-22:{{revision}}
    - name: build-platforms
      value:
        - linux/x86_64
    - name: dockerfile
      value: .konflux/Dockerfile
    - name: hermetic
      value: "true"
    - name: prefetch-input
      value: ""
    - name: build-source-image
      value: "true"
    - name: skip-sast-coverity
      value: "true"
    - name: additional-tags
      value: ['latest']
    - name: additional-labels
      value:
        - name=openshift4/o-cloud-manager-rhel9-operator
  pipelineRef:
    name: build-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-o-cloud-manager-4-22
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
