apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/openshift-kni/oran-o2ims?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: |
      event == "push" &&
      target_branch == "release-4.21" &&
      (
        '.konflux/catalog/***'.pathChanged() ||
        '.konflux/Dockerfile.catalog'.pathChanged() ||
        '.tekton/fbc-pipeline.yaml'.pathChanged() ||
        '.tekton/images-mirror-set.yaml'.pathChanged() ||
        '.tekton/o-cloud-manager-fbc-4-21-push.yaml'.pathChanged() ||
        'telco5g-konflux'.pathChanged() ||
        'telco5g-konflux/***'.pathChanged()
      )
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: o-cloud-manager-fbc-4-21
    appstudio.openshift.io/component: o-cloud-manager-fbc-4-21
    pipelines.appstudio.openshift.io/type: build
  name: o-cloud-manager-fbc-4-21-on-push
  namespace: telco-5g-tenant
spec:
  params:
    - name: git-url
      value: '{{source_url}}'
    - name: revision
      value: '{{revision}}'
    - name: output-image
      value: quay.io/redhat-user-workloads/telco-5g-tenant/o-cloud-manager-fbc-4-21:{{revision}}
    - name: build-platforms
      value:
        - linux/x86_64
    - name: dockerfile
      value: .konflux/Dockerfile.catalog
    - name: hermetic
      value: "true"
    - name: additional-tags
      value: ['latest']
  pipelineRef:
    name: fbc-pipeline
  taskRunTemplate:
    serviceAccountName: build-pipeline-o-cloud-manager-fbc-4-21
  workspaces:
    - name: git-auth
      secret:
        secretName: '{{ git_auth_secret }}'
status: {}
