# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: generated
output: client.gen.go

generate:
  client: true
  models: true
  embedded-spec: true

output-options:
  skip-fmt: false
  skip-prune: true
  nullable-type: true
  name-normalizer: ToCamelCaseWithDigits

import-mapping:
  ../../common/api/openapi.yaml: "github.com/openshift-kni/oran-o2ims/internal/service/common/api/generated"
