# These resources constitute the fully configured set of manifests
# used to generate the 'manifests/' directory in a bundle.
resources:
- bases/oran-o2ims.clusterserviceversion.yaml
- ../crd
- ../default
- ../samples
- ../scorecard
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
