# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: generated
output: ../generated/inventory.generated.go

generate:
  std-http-server: true
  client: false
  models: true
  embedded-spec: true
  strict-server: true

output-options:
  skip-fmt: false
  skip-prune: true
  nullable-type: true
  name-normalizer: ToCamelCaseWithDigits

import-mapping:
  ../../common/api/openapi.yaml: "github.com/openshift-kni/oran-o2ims/internal/service/common/api/generated"
