apiVersion: clcm.openshift.io/v1alpha1
kind: HardwareProfile
metadata:
  name: dell-xr8620t-bios-2.6.3-bmc-7.20.30.50
  namespace: oran-o2ims
spec:
  bios:
    attributes:
      SysProfile: Custom
      WorkloadProfile: TelcoOptimizedProfile
      SriovGlobalEnable: Enabled
      AcPwrRcvryUserDelay: 120
  biosFirmware:
    version: 2.6.3
    url: https://example.com:8888/firmware/xr8620t/BIOS_M3M7R_WN64_2.6.3.EXE
  bmcFirmware:
    version: 7.20.30.50
    url: https://example.com:8888/firmware/xr8620t/iDRAC-with-Lifecycle-Controller_Firmware_CJKPX_WN64_7.20.30.50_A00.EXE
