---
name: Kustomize Validation

on:  # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  kustomize-validation:
    name: Validate Kustomization Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: actionlint
        uses: raven-actions/actionlint@v2

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Install Kustomize
        run: |
          # Use the Makefile to install kustomize with the version specified in KUSTOMIZE_VERSION
          make kustomize

          # Add the bin directory to PATH for subsequent steps
          echo "${PWD}"/bin >> "${GITHUB_PATH}"

          # Verify installation
          "${PWD}"/bin/kustomize version

      - name: Validate Kustomization Files
        run: make test-kustomize
