# We use this IDMS to check if the images in the FBC are resolvable using the staging or production catalog.
# https://github.com/konflux-ci/community-catalog/tree/development/pipelines/validate-fbc-images-resolvable
apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
  name: fbc-images-resolvable-integration-test-idms
spec:
  imageDigestMirrors:
    - mirrors:
        - registry.stage.redhat.io/openshift4/o-cloud-manager-rhel9-operator
      source: registry.redhat.io/openshift4/o-cloud-manager-rhel9-operator
    - mirrors:
        - registry.stage.redhat.io/openshift4/o-cloud-manager-operator-bundle
      source: registry.redhat.io/openshift4/o-cloud-manager-operator-bundle
